#!/bin/sh

# User specific aliases and functions
alias h='history'

alias ls='ls -h --color'
alias ll='ls -al'

alias dps='/usr/bin/docker ps --format "table {{.ID}}\t{{.Image}}\t{{.Ports}}\t{{.Status}}\t{{.Names}}"'
alias dim='/usr/bin/docker images'

