set mousehide

map <S-Insert> <MiddleMouse>
map! <S-Insert> <MiddleMouse>

if version >= 500

  let c_comment_strings=1

  if !exists("syntax_on")
    syntax on
  endif

  set hlsearch

  colorscheme desert
  set guifont=Liberation\ Mono\ 8

  set guioptions-=T
  set guioptions-=r
  set guioptions-=L

endif
