#!/bin/sh

# Get my aliases and functions
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

# Get work aliases and functions
if [ -f ~/.bashrc_wk ]; then
  . ~/.bashrc_office
fi

# User specific environment and startup programs
export HISTSIZE=3000
export EDITOR=vim
export VISUAL=vim
export SVN_EDITOR=vim
export GIT_EDITOR=vim
export PATH="/usr/local/sbin:/usr/sbin:/sbin:${PATH}"

# Oracle JDK
export JAVA_HOME=~/development/java/jdk/jdk
export JDK_HOME="${JAVA_HOME}"
export JRE_HOME="${JAVA_HOME}/jre"
export PATH="${JAVA_HOME}/bin:${PATH}"

# Swing apps work with DWM
wmname LG3D
unset AWT_TOOLKIT

# Ant
export ANT_HOME=~/development/java/ant/ant
export PATH="${ANT_HOME}/bin:${PATH}"

# Maven
export MAVEN_HOME=~/development/java/maven/maven
export PATH="${MAVEN}/bin:${PATH}"

# Gradle
export GRADLE_HOME=~/development/java/gradle/gradle
export PATH="${GRADLE_HOME}/bin:${PATH}"

# Groovy
export GROOVY_HOME=~/development/groovy/groovy
export PATH="${GROOVY_HOME}/bin:${PATH}"

# Scala
export SCALA_HOME=~/development/scala/scala
export PATH="${PATH}:${SCALA_HOME}/bin"

# Apache Spark
export SPARK_HOME=~/development/spark/spark
export PATH="${SPARK_HOME}/bin:${PATH}"

# IntelliJ
export INTELLIJ_HOME=~/development/java/intellij/intellij
export PATH="${INTELLIJ_HOME}/bin:${PATH}"

# Eclipse
export ECLIPSE_HOME=~/development/java/eclipse/eclipse
export PATH="${ECLIPSE_HOME}:${PATH}"

# SQuirrel SQL
export SQUIRREL_HOME=~/development/database/squirrel/squirrel-sql
export PATH="${SQUIRREL_HOME}:${PATH}"

# DBeaver
export DBEAVER_HOME=~/development/database/dbeaver/dbeaver
export PATH="${DBEAVER_HOME}:${PATH}"

# Robo3T
export ROBO3T_HOME=~/development/database/mongo/robo3t
export PATH="${ROBO3T_HOME}/bin:${PATH}"

# JMeter
export JMETER_HOME=~/development/java/jmeter/jmeter
export PATH="${JMETER_HOME}/bin:${PATH}"

# SOAP UI
export SOAPUI_HOME=~/development/soap/soapui/soapui
export PATH="${SOAPUI_HOME}/bin:${PATH}"

# Node
export NODE_HOME=~/development/node/runtime/node
export PATH="${NODE_HOME}/bin:${PATH}"

