#!/bin/sh

# Get my aliases and functions
if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

# User specific environment and startup programs
export HISTSIZE=3000
export EDITOR=vim
export VISUAL=vim
export SVN_EDITOR=vim
export GIT_EDITOR=vim
export PATH="/usr/local/sbin:/usr/sbin:/sbin:${PATH}"

# Swing apps works with DWM
if [ -n "${DISPLAY}" ]; then
  export _JAVA_AWT_WM_NONREPARENTING=1
fi

